# 标注了'FIXME'的是必须赋值的参数
# 标注了'CHANGED'的是可能需要修改的参数
# 标注了'NOTE'的是也许使用默认值即可的参数


[postgresql]
# 数据库连接参数
host = '127.0.0.1'                              # CHANGED: PostgreSQL服务器地址
port = 5432                                     # NOTE: PostgreSQL服务器端口
user = 'postgres'                               # FIXME: PostgreSQL用户名
password = 'postgres'                           # FIXME: PostgreSQL密码
dbname = 'postgres'                             # CHANGED: 要使用的数据库名
schema = 'public'                               # CHANGED: 当数据没有自述存储的Schema时的默认值
table = 'data'                                  # CHANGED: 当数据没有自述存储的Table时的默认值
    [postgresql.pool]
    # 数据库连接池配置信息
    mincached = 10                              # NOTE: 池中空闲连接初始数量，default = 10
    maxcached = 0                               # NOTE: 池中最大空闲连接数，0或None表示池大小不受限制
    maxshared = 0                               # NOTE: 共享连接的最大数目，0或None表示所有连接都是专用的
    maxconnections = 0                          # NOTE: 通常允许的最大连接数，0或None表示不受限制
    blocking = true                             # NOTE: 连接数超出最大值时的行为，true表示阻塞直到有连接可用，false表示报告错误
    maxusage = 0                                # NOTE: 单个连接的最大复用次数，当达到该次数时该连接自动重置，0或None表示无限制
    ping = 1                                    # NOTE: 何时检查连接：0/None - 永不；1(default) - 从pool中获取连接时；2 - 创建cursor时；4 - 执行查询时；7 - 始终
    [postgresql.column]
    # 定义数据表的固有列名
    column_ts = 'timestamp'                     # CHANGED: 时间戳列名
    column_id = 'deviceid'                      # CHANGED: ID列名
    [postgresql.message]
    # message数据配置
    message_switch = true                       # CHANGED: 是否要将数据中的message数据集中到独立的表里
    message_flag = 'message'                    # CHANGED: message的键名，用来判断是否采集到了message信息
    message_schema = 'public'                   # CHANGED: 独立message的schema
    message_table = 'message'                   # CHANGED: 独立message的table
    message_column = [                          # CHANGED: 独立message的column
        'message', 'level',
        'source', 'logpath',
    ]
